import Layout from "@/components/Layout";

const PrivacyPolicy = () => (
  <Layout>
    <section className="px-4 py-16 md:py-24">
      <div className="container mx-auto max-w-3xl space-y-8">
        <div className="space-y-4">
          <p className="text-sm uppercase tracking-[0.24em] text-primary">Policy</p>
          <h1 className="font-heading text-section-sm md:text-section">Privacy Policy</h1>
          <p className="text-body-lg text-muted-foreground">
            Memento is designed to handle highly sensitive care information. This
            summary explains how the app stores data and how we limit access inside
            the product.
          </p>
        </div>

        <div className="space-y-6 rounded-3xl border bg-card p-8 shadow-sm">
          <div className="space-y-2">
            <h2 className="text-xl font-bold">What We Store</h2>
            <p className="text-muted-foreground">
              Caregiver login credentials, patient IDs, care plans, medication
              schedules, emergency contacts, task history, and day summaries are
              stored so the caregiver and patient portals stay synchronized.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-bold">How Access Works</h2>
            <p className="text-muted-foreground">
              Caregivers sign in with email and password. Patients sign in with a
              unique patient ID generated by their caregiver. Portal access is
              role-restricted so each user only sees the dashboard intended for
              them.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-bold">Data Protection</h2>
            <p className="text-muted-foreground">
              Passwords are stored in hashed form. Care data is separated by patient
              and caregiver identifiers so updates apply only to the linked record.
            </p>
          </div>

          <div className="space-y-2">
            <h2 className="text-xl font-bold">Support Requests</h2>
            <p className="text-muted-foreground">
              Messages sent through the public contact form are stored only to help
              the support workflow and diagnose product issues.
            </p>
          </div>
        </div>
      </div>
    </section>
  </Layout>
);

export default PrivacyPolicy;
